version: '2'

services:

  adminer:

    image: adminer
    restart: always
    ports:
      - 8081:8080

#  dynamodb:
#
#    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
##    environment:
##      - ./Djava.library.path=./DynamoDBLocal_lib
#    image: amazon/dynamodb-local:latest
#    ports:
#      - 8000:8000
#    volumes:
#      - ./dynamodb/data:/home/dynamodblocal/data
#    working_dir: /home/dynamodblocal

  elasticsearch:

    image: elasticsearch:7.5.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  jenkins:
    build:
      context: ./jenkins
    ports:
      - 8083:8080
      - 50000:50000
    volumes:
      - jenkins:/var/jenkins_home

  kibana:

    depends_on:
      - elasticsearch
    image: kibana:7.5.0
    ports:
      - 5601:5601

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567-4584:4567-4584"
      - 8082:8080
    environment:
      - DATA_DIR="/tmp/localstack/data"
#      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
      - LAMBDA_EXECUTOR=local
      - PORT_WEB_UI=8080
      - SERVICES=lambda,s3,ses,sns,sqs,ssm,secretsmanager
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack:/tmp/localstack/data

  mysql:

    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
    image: mysql:8.0.18
    ports:
      - 3307:3306
    restart: always
    volumes:
      - mysql:/var/lib/mysql

  nginx:

    build:
      context: ./nginx
    depends_on:
      - php-fpm
    ports:
      - 80:80
    restart: always
    volumes:
      - ../apps/:/var/www
      - ./nginx/sites-available:/etc/nginx/sites-available

  php-fpm:

    build:
      context: ./php-fpm
    expose:
      - 9000
    restart: always
    volumes:
      - ../apps/:/var/www

  redis:

    image: redis:latest
    restart: always

  splunk:

    environment:
      SPLUNK_PASSWORD: test1234
      SPLUNK_START_ARGS: --accept-license
    image: store/splunk/splunk:7.3
    ports:
      - 8001:8000
      - 8089:8089
    volumes:
      - splunk-etc:/opt/splunk/etc
      - splunk-var:/opt/splunk/var

  splunk-listener:

    environment:
      SPLUNK_START_ARGS: --accept-license
    image: store/splunk/universalforwarder:7.3
    volumes:
      - ubuntu-projects:/opt/projects

  ubuntu:
  
    build:
      context: ./ubuntu
    environment:
      DISABLE_SYSLOG: 0
      DISABLE_SSH: 0
      DISABLE_CRON: 1
    expose:
      - 222
    ports:
      - 222:222
      - 13001:13001
    restart: always
    volumes:
      - splunk-listener:/opt/splunk
      - ubuntu-projects:/root/projects

volumes:

  elasticsearch:
  jenkins:
  localstack:
  mysql:
  splunk-etc:
  splunk-listener:
  splunk-var:
  ubuntu-projects:
